# Generated by Django 3.1.2 on 2020-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdhRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.IntegerField(unique=True)),
                ('object_id', models.IntegerField(unique=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=300)),
                ('geometry', models.TextField()),
                ('geometry_type', models.CharField(max_length=20)),
                ('coordinates', models.TextField()),
            ],
        ),
    ]
